export const IPC = {
  projectsList: 'projects:list',
  projectsCreate: 'projects:create',
  sldsListByProject: 'slds:listByProject',
  sldsUpload: 'slds:upload',
  sldsDelete: 'slds:delete',
  sldsReadFile: 'slds:readFile',
  annotationsListBySldAndPage: 'annotations:listBySldAndPage',
  annotationsCreate: 'annotations:create',
  annotationsDelete: 'annotations:delete',
  catalogGetStatus: 'catalog:getStatus',
  catalogReload: 'catalog:reload',
  catalogSearch: 'catalog:search',
  aiExtractSld: 'ai:extractSld',
  aiGetExtraction: 'ai:getExtraction',
  aiExtractionProgress: 'ai:extractionProgress',
  quotationsGenerate: 'quotations:generate',
  quotationsGetBySld: 'quotations:getBySld',
  quotationsListByProject: 'quotations:listByProject',
  quotationsExport: 'quotations:export'
} as const
